{{- if .Values.dataexchange.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "firefly.fullname" . }}-dx
  labels:
    {{- include "firefly.dataexchangeLabels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "firefly.fullname" . }}-dx
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "firefly.dataexchangeSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/dataexchange/secret.yaml") . | sha256sum }}
        {{- if .Values.dataexchange.certificate.enabled }}
        checksum/certificate: {{ include (print $.Template.BasePath "/dataexchange/certificate.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.dataexchange.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "firefly.dataexchangeSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dataexchange.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.dataexchange.podSecurityContext | nindent 8 }}
      containers:
        - name: dx
          securityContext:
            {{- toYaml .Values.dataexchange.securityContext | nindent 12 }}
          image: "{{ .Values.dataexchange.image.repository }}:{{ .Values.dataexchange.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dataexchange.image.pullPolicy }}
          {{- if .Values.dataexchange.extraEnv }}
          env:
            {{- toYaml .Values.dataexchange.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.dataexchange.service.apiPort }}
              protocol: TCP
            - name: p2p
              containerPort: {{ .Values.dataexchange.service.p2pPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            failureThreshold: 5
            successThreshold: 1
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: p2p
            initialDelaySeconds: 5
            failureThreshold: 10
            successThreshold: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.dataexchange.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/peer-certs
              subPath: peer-certs
              name: {{ include "firefly.fullname" . }}-dx-peers
            - mountPath: /data/peers
              subPath: peers
              name: {{ include "firefly.fullname" . }}-dx-peers
            - mountPath: /data/config.json
              name: config
              subPath: config.json
            - mountPath: /data/key.pem
              name: tls
              subPath: tls.key
            - mountPath: /data/cert.pem
              name: tls
              subPath: tls.crt
            - mountPath: /data/ca.pem
              name: tls
              subPath: ca.crt
            - mountPath: /data/blobs
              {{- if and .Values.dataexchange.persistentVolumes.blobs.enabled .Values.dataexchange.persistentVolumes.blobs.subPath }}
              subPath: {{ .Values.dataexchange.persistentVolumes.blobs.subPath | quote }}
              {{- end }}
              name: {{ include "firefly.fullname" . }}-dx-blobs
      {{- with .Values.dataexchange.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataexchange.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataexchange.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: "{{ include "firefly.fullname" . }}-dx-config"
        - name: tls
          secret:
            secretName: {{ if and .Values.dataexchange.certificate.enabled (not .Values.dataexchange.tlsSecret.enabled) }}"{{ include "firefly.fullname" . }}-dx-tls"{{ else }}{{ .Values.dataexchange.tlsSecret.name }}{{ end }}
        {{- if not .Values.dataexchange.persistentVolumes.blobs.enabled }}
        - name: {{ include "firefly.fullname" . }}-dx-blobs
          emptyDir: {}
        {{- end }}
        {{- if not .Values.dataexchange.persistentVolumes.peers.enabled }}
        - name: {{ include "firefly.fullname" . }}-dx-peers
          emptyDir: {}
  {{- end }}
  {{- if or .Values.dataexchange.persistentVolumes.blobs.enabled .Values.dataexchange.persistentVolumes.peers.enabled }}
  volumeClaimTemplates:
    {{- if .Values.dataexchange.persistentVolumes.blobs.enabled }}
    - metadata:
      {{- with .Values.dataexchange.persistentVolumes.blobs }}
        name: {{ include "firefly.fullname" . }}-dx-blobs
        {{ with .annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .accessModes | nindent 10 }}
        storageClassName: {{ .storageClass }}
        resources:
          requests:
            storage: {{ .size }}
      {{- end }}
    {{- end }}
    {{- if .Values.dataexchange.persistentVolumes.peers.enabled }}
      - metadata:
        {{- with .Values.dataexchange.persistentVolumes.peers }}
        name: {{ include "firefly.fullname" . }}-dx-peers
        {{ with .annotations }}
        annotations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      spec:
        accessModes:
        {{- toYaml .accessModes | nindent 10 }}
        storageClassName: {{ .storageClass }}
        resources:
          requests:
            storage: {{ .size }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
