repository: hyperledger/firefly
remote_theme: pmarsceill/just-the-docs
logo: "images/hyperledger-firefly_color.svg"
title: Hyperledger FireFly Docs
baseurl: /firefly
aux_links:
  "GitHub":
    - "//github.com/hyperledger/firefly"
  "Wiki":
    - "https://wiki.hyperledger.org/display/FIR"
  "Chat":
    - "https://chat.hyperledger.org/channel/firefly"
  "Mailing List":
    - "https://lists.hyperledger.org/g/firefly"
  "Calendar":
    - "https://lists.hyperledger.org/g/firefly/calendar"

remote_theme: pmarsceill/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
