remote_theme: pmarsceill/just-the-docs
logo: "firefly_logo.png"
title: Hyperledger FireFly Docs
aux_links:
  "GitHub":
    - "//github.com/hyperledger/firefly"
  "Wiki":
    - "https://wiki.hyperledger.org/display/FIR"
  "Chat":
    - "https://chat.hyperledger.org/channel/firefly"
  "Mailing List":
    - "https://lists.hyperledger.org/g/firefly"
  "Calendar":
    - "https://lists.hyperledger.org/g/firefly/calendar"

theme: just-the-docs
