repository: hyperledger/firefly
logo: "images/hyperledger-firefly_color.svg"
title: Hyperledger FireFly Docs
baseurl: /firefly
aux_links:
  "GitHub":
    - "https://github.com/hyperledger/firefly"
  "Wiki":
    - "https://wiki.hyperledger.org/display/FIR"
  "Discord":
    - "https://discord.gg/hyperledger"
color_scheme: firefly
plugins:
  - jekyll-multiple-languages-plugin
languages: ["en"]
